'use client';

import { useEffect, useState, CSSProperties } from 'react';

// ─── Refinery Facility Units with Exact Map Coordinates (%) ───────────────────
export interface FacilityUnit {
  id: string;
  name: string;
  code: string;
  category: 'crude' | 'process' | 'utilities' | 'storage' | 'logistics' | 'admin' | 'safety';
  x: number;      // left percentage (0 - 100)
  y: number;      // top percentage (0 - 100)
  w: number;      // width percentage
  h: number;      // height percentage
  riskScore: number;
  incidents: number;
  lastIncident: string | null;
  dominantHazard: string;
  status: 'critical' | 'high' | 'medium' | 'low' | 'normal';
  details: string;
}

export const REFINERY_FACILITY_UNITS: FacilityUnit[] = [
  {
    id: 'unit-adu',
    name: 'Atmospheric Distillation Unit (ADU)',
    code: 'ADU-01',
    category: 'process',
    x: 25.5,
    y: 35.5,
    w: 10.5,
    h: 24,
    riskScore: 92,
    incidents: 6,
    lastIncident: '2026-09-09T08:22:00.000Z',
    dominantHazard: 'Flammable vapor leak & elevated thermal radiation',
    status: 'critical',
    details: 'Primary fractionation column experiencing pressure flange wear. High risk of hydrocarbon leak.',
  },
  {
    id: 'unit-vdu',
    name: 'Vacuum Distillation Unit (VDU)',
    code: 'VDU-02',
    category: 'process',
    x: 36.2,
    y: 35.5,
    w: 10.5,
    h: 24,
    riskScore: 78,
    incidents: 4,
    lastIncident: '2026-09-08T14:10:00.000Z',
    dominantHazard: 'Vacuum ejector temperature deviation',
    status: 'high',
    details: 'Heavy gas oil stripper pump vibration alert. Secondary seal inspection pending.',
  },
  {
    id: 'unit-hdt',
    name: 'Hydrotreater Unit (HDT)',
    code: 'HDT-03',
    category: 'process',
    x: 46.9,
    y: 35.5,
    w: 9.8,
    h: 24,
    riskScore: 85,
    incidents: 5,
    lastIncident: '2026-09-09T11:45:00.000Z',
    dominantHazard: 'High pressure Hydrogen (H2) line corrosion',
    status: 'critical',
    details: 'Desulfurization reactor bed delta-P elevated. Hydrogen circuit flange inspection scheduled.',
  },
  {
    id: 'unit-fcc',
    name: 'Fluid Catalytic Cracking (FCC)',
    code: 'FCC-04',
    category: 'process',
    x: 56.9,
    y: 35.5,
    w: 8.8,
    h: 24,
    riskScore: 95,
    incidents: 8,
    lastIncident: '2026-09-10T19:30:00.000Z',
    dominantHazard: 'Regenerator cyclone erosion & catalyst hot-spot',
    status: 'critical',
    details: 'Active warning: Catalyst slide valve differential pressure fluctuating near upper threshold.',
  },
  {
    id: 'unit-reformer',
    name: 'Reformer Unit',
    code: 'REF-05',
    category: 'process',
    x: 65.9,
    y: 35.5,
    w: 8.5,
    h: 24,
    riskScore: 68,
    incidents: 3,
    lastIncident: '2026-09-06T11:20:00.000Z',
    dominantHazard: 'Furnace coil localized overheating',
    status: 'high',
    details: 'Naphtha hydrotreater booster compressor seal oil replacement due.',
  },
  {
    id: 'unit-desalting',
    name: 'Desalting & Pre-heat Train',
    code: 'DESALT-00',
    category: 'process',
    x: 25.5,
    y: 25.5,
    w: 22.5,
    h: 9.5,
    riskScore: 54,
    incidents: 2,
    lastIncident: '2026-09-03T15:00:00.000Z',
    dominantHazard: 'Electrical grid transformer oil leakage',
    status: 'medium',
    details: 'Electrostatic desalter water cut sensors operational. Desalter mud wash valve serviced.',
  },
  {
    id: 'unit-crude-storage',
    name: 'Crude Oil Storage Farm (T-101 to T-104)',
    code: 'CRUDE-FARM',
    category: 'crude',
    x: 3.8,
    y: 25.5,
    w: 19.5,
    h: 24,
    riskScore: 74,
    incidents: 3,
    lastIncident: '2026-09-07T09:15:00.000Z',
    dominantHazard: 'Floating roof rim seal gap & VOC vapor emission',
    status: 'high',
    details: 'Tank T-102 hydrocarbon gas detector triggered low LEL alarm during morning sun expansion.',
  },
  {
    id: 'unit-firewater',
    name: 'Firewater Tank Farm & Pump House',
    code: 'FW-PUMP',
    category: 'safety',
    x: 3.8,
    y: 51.5,
    w: 19.5,
    h: 14,
    riskScore: 32,
    incidents: 1,
    lastIncident: '2026-08-28T10:00:00.000Z',
    dominantHazard: 'Backup diesel pump battery charging voltage low',
    status: 'low',
    details: 'Main electric jockey pump active at 11.2 bar. Ring main pressure nominal.',
  },
  {
    id: 'unit-cooling-tower',
    name: 'Cooling Tower Area',
    code: 'CT-ZONE',
    category: 'utilities',
    x: 3.8,
    y: 67.5,
    w: 19.5,
    h: 14.5,
    riskScore: 42,
    incidents: 2,
    lastIncident: '2026-09-04T12:00:00.000Z',
    dominantHazard: 'Slip hazard on fan deck walkways & Legionella biocides',
    status: 'medium',
    details: 'Tower Cell #2 vibration sensor flagged blade pitch imbalance.',
  },
  {
    id: 'unit-power-plant',
    name: 'Utilities & Offsites: Power Plant & Boiler House',
    code: 'UTIL-PWR',
    category: 'utilities',
    x: 3.8,
    y: 10.5,
    w: 22,
    h: 13,
    riskScore: 65,
    incidents: 3,
    lastIncident: '2026-09-05T13:15:00.000Z',
    dominantHazard: 'High pressure steam line (HP 42 bar) thermal insulation breakdown',
    status: 'high',
    details: 'Boiler #1 economizer tube soot blowing scheduled. Steam trap survey underway.',
  },
  {
    id: 'unit-water-treatment',
    name: 'Water Treatment Plant (WTP & ETP)',
    code: 'WTP-01',
    category: 'utilities',
    x: 27.0,
    y: 10.5,
    w: 15.5,
    h: 13,
    riskScore: 28,
    incidents: 1,
    lastIncident: '2026-09-01T16:00:00.000Z',
    dominantHazard: 'Hydrochloric Acid / Caustic dosing splash hazard',
    status: 'low',
    details: 'pH balancing ponds within environmental consent levels. Clarifier skimmers clean.',
  },
  {
    id: 'unit-admin',
    name: 'Administration Building',
    code: 'ADMIN-HQ',
    category: 'admin',
    x: 44.5,
    y: 10.5,
    w: 18.5,
    h: 13,
    riskScore: 12,
    incidents: 0,
    lastIncident: null,
    dominantHazard: 'None (Safe Zone)',
    status: 'normal',
    details: 'Executive and site compliance offices. HVAC air intake positive pressure verified.',
  },
  {
    id: 'unit-control-room',
    name: 'Main Central Control Room (DCS)',
    code: 'CCR-01',
    category: 'admin',
    x: 64.5,
    y: 10.5,
    w: 10.8,
    h: 13,
    riskScore: 18,
    incidents: 0,
    lastIncident: null,
    dominantHazard: 'UPS Battery rack hydrogen buildup monitoring',
    status: 'normal',
    details: 'Blast-proof pressurized enclosure. Redundant DCS controllers active.',
  },
  {
    id: 'unit-lab',
    name: 'Quality Assurance Testing Laboratory',
    code: 'QA-LAB',
    category: 'admin',
    x: 76.5,
    y: 10.5,
    w: 8.8,
    h: 13,
    riskScore: 35,
    incidents: 1,
    lastIncident: '2026-09-02T10:45:00.000Z',
    dominantHazard: 'Fume hood face velocity deviation & volatile sample storage',
    status: 'low',
    details: 'Octane test engine exhaust inspected. Chemical inventory logged.',
  },
  {
    id: 'unit-assembly-north',
    name: 'Emergency Assembly Point (North)',
    code: 'EAP-N',
    category: 'safety',
    x: 86.5,
    y: 10.5,
    w: 10.5,
    h: 13,
    riskScore: 5,
    incidents: 0,
    lastIncident: null,
    dominantHazard: 'None (Designated Safe Refuge)',
    status: 'normal',
    details: 'Windsock functional. Emergency siren and headcount beacon verified.',
  },
  {
    id: 'unit-product-storage',
    name: 'Product Storage & Loading (T-201 to T-204)',
    code: 'PROD-STORE',
    category: 'storage',
    x: 76.0,
    y: 25.5,
    w: 20.5,
    h: 40.5,
    riskScore: 82,
    incidents: 5,
    lastIncident: '2026-09-09T18:00:00.000Z',
    dominantHazard: 'Static charge generation during diesel/gasoline tank loading',
    status: 'critical',
    details: 'Gantry loading bay #3 grounding interlock failed continuity test. Repaired today.',
  },
  {
    id: 'unit-separation-blending',
    name: 'Product Separation & Gasoline Blending',
    code: 'BLEND-01',
    category: 'storage',
    x: 25.5,
    y: 62.5,
    w: 22.5,
    h: 18.5,
    riskScore: 62,
    incidents: 3,
    lastIncident: '2026-09-05T07:50:00.000Z',
    dominantHazard: 'Additive dosing pump seal leak',
    status: 'high',
    details: 'Anti-knock additive injection skid calibrated. Nitrogen blanketing active.',
  },
  {
    id: 'unit-storage-intermediate',
    name: 'Storage Tanks Intermediate (T-301 to T-304)',
    code: 'INT-TANKS',
    category: 'storage',
    x: 49.0,
    y: 62.5,
    w: 15.5,
    h: 18.5,
    riskScore: 48,
    incidents: 2,
    lastIncident: '2026-09-04T09:00:00.000Z',
    dominantHazard: 'Berm bund wall drain valve housekeeping',
    status: 'medium',
    details: 'Intermediate kerosene and naphtha cut tanks. Level gauges within calibration.',
  },
  {
    id: 'unit-workshop',
    name: 'Maintenance Workshop & Tooling',
    code: 'MAINT-SHOP',
    category: 'logistics',
    x: 65.5,
    y: 62.5,
    w: 9.5,
    h: 18.5,
    riskScore: 45,
    incidents: 2,
    lastIncident: '2026-09-03T14:30:00.000Z',
    dominantHazard: 'Hot work welding sparks near flammable boundary',
    status: 'medium',
    details: 'LOTO gear depot and valve refurbishment lathe bay. Hot work permits active: 2.',
  },
  {
    id: 'unit-warehouse',
    name: 'Central Warehouse & Spare Parts Depot',
    code: 'WH-MAIN',
    category: 'logistics',
    x: 76.0,
    y: 67.5,
    w: 10.5,
    h: 15.5,
    riskScore: 30,
    incidents: 1,
    lastIncident: '2026-09-02T14:50:00.000Z',
    dominantHazard: 'Forklift pedestrian crossing near high-bay racks',
    status: 'low',
    details: 'Forklift battery charging area ventilation verified. Flammable paint locker locked.',
  },
  {
    id: 'unit-medical',
    name: 'Medical Center & Occupational Health',
    code: 'MED-01',
    category: 'safety',
    x: 87.5,
    y: 67.5,
    w: 9.0,
    h: 15.5,
    riskScore: 8,
    incidents: 0,
    lastIncident: null,
    dominantHazard: 'None (First Aid / Triage Station)',
    status: 'normal',
    details: 'Paramedic team on duty. 2 emergency ambulances stationed at bay.',
  },
  {
    id: 'unit-rail-loading',
    name: 'Rail Loading & Unloading Terminal',
    code: 'RAIL-TERM',
    category: 'logistics',
    x: 3.8,
    y: 84.5,
    w: 33.5,
    h: 10.5,
    riskScore: 76,
    incidents: 4,
    lastIncident: '2026-09-08T09:30:00.000Z',
    dominantHazard: 'Track bonding grounding & wagon top spill risk',
    status: 'high',
    details: 'Wagon rake grounding check completed. Overfill shut-off sensors tested.',
  },
  {
    id: 'unit-parking',
    name: 'Authorized Vehicle Parking & Gate 2',
    code: 'PARK-S',
    category: 'logistics',
    x: 39.0,
    y: 84.5,
    w: 24.5,
    h: 10.5,
    riskScore: 15,
    incidents: 0,
    lastIncident: null,
    dominantHazard: 'Traffic routing & ignition source control',
    status: 'normal',
    details: 'Spark arrestor enforcement for contractor pickup trucks entering perimeter.',
  },
  {
    id: 'unit-security',
    name: 'South Gate & Security Control',
    code: 'SEC-SOUTH',
    category: 'safety',
    x: 64.5,
    y: 84.5,
    w: 9.0,
    h: 10.5,
    riskScore: 10,
    incidents: 0,
    lastIncident: null,
    dominantHazard: 'None (Perimeter Access Control)',
    status: 'normal',
    details: 'Automated biometric card readers & alcohol breathalyzer check in force.',
  },
  {
    id: 'unit-assembly-south',
    name: 'Emergency Assembly Point (South)',
    code: 'EAP-S',
    category: 'safety',
    x: 77.5,
    y: 84.5,
    w: 19.0,
    h: 10.5,
    riskScore: 5,
    incidents: 0,
    lastIncident: null,
    dominantHazard: 'None (Designated Safe Refuge)',
    status: 'normal',
    details: 'Primary south evacuation muster area. Clear access from distillation block.',
  },
];

// ─── Visual Risk Styling ───────────────────────────────────────────────────────
export function getUnitRiskColor(score: number): string {
  if (score >= 80) return '#dc2626'; // Safety Red
  if (score >= 60) return '#ea580c'; // Signal Orange
  if (score >= 40) return '#d97706'; // Hazard Amber
  if (score >= 20) return '#16a34a'; // Low / Safe Green
  return '#10b981'; // Normal Safe
}

export function getUnitRiskOverlay(score: number): { fill: string; border: string; glow: string } {
  if (score >= 80) {
    return {
      fill: 'rgba(220, 38, 38, 0.42)',
      border: '#dc2626',
      glow: 'rgba(220, 38, 38, 0.6)',
    };
  }
  if (score >= 60) {
    return {
      fill: 'rgba(234, 88, 12, 0.38)',
      border: '#ea580c',
      glow: 'rgba(234, 88, 12, 0.5)',
    };
  }
  if (score >= 40) {
    return {
      fill: 'rgba(217, 119, 6, 0.32)',
      border: '#d97706',
      glow: 'rgba(217, 119, 6, 0.4)',
    };
  }
  if (score >= 20) {
    return {
      fill: 'rgba(22, 163, 74, 0.22)',
      border: '#16a34a',
      glow: 'rgba(22, 163, 74, 0.3)',
    };
  }
  return {
    fill: 'rgba(16, 185, 129, 0.15)',
    border: '#10b981',
    glow: 'transparent',
  };
}
